baseURL = 'http://carcdr.net/'
languageCode = 'en-us'
title = '(car . cdr)'

[params]
  description = 'Project Documentation'
  author = 'Ed Paget'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
